#Join Frames

```{r echo=FALSE, warning=FALSE, error=FALSE, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
detach("package:plyr", unload=TRUE)
detach("package:dplyr", unload=TRUE)
library(knitr)
library(tidyr)

library(dplyr)
#library(plyr)

library(lubridate)
library(magrittr)
library(dummies)

#Load files
load('processed_files/account')
load('processed_files/card')
load('processed_files/client')
load('processed_files/demographic')
load('processed_files/disposition')
load('processed_files/loan')
load('processed_files/order')

#load('processed_files/transaction')
```

## Join frames without transactions:


```{r echo = FALSE, warning=FALSE}

#Base frame accounts 
frame_no_transaction <- account %>%
  #Join accounts
  left_join(loan, by = 'account_id') %>%
  #Join Demographie
  left_join(demographic, by = 'district_id') %>%
  #Join disposition
  left_join(
    dplyr::filter(disposition, type == 'OWNER' ) %>% 
      left_join(disposition %>% group_by(account_id) %>% dplyr::summarise(dependants = n()-1), by = 'account_id')
    , by = 'account_id') %>%
  #Join client
  left_join(client,by = 'client_id') %>%
  #Join card
  left_join(card, by = 'disp_id') %>%
  #Join transactions 
  left_join(
    transaction %>% group_by(account_id) %>% dplyr::summarise(amount_transactions = sum(amount)),
    by = 'account_id')

save(frame_no_transaction,file = 'processed_files/frame_no_transaction')

```

## Create Clusters

```{r echo = FALSE, warning=FALSE}

cluster <- frame_no_transaction %>% 
  
  select(`average salary`, amount_transactions, birth_number, `unemploymant rate '96`, dependants,`enterpreneurs per 1000 inhabitants`  ) %>%
  
  cbind(dummy(frame_no_transaction$gender)) %>%
  
  cbind(dummy(frame_no_transaction$status)) %>%
  
  kmeans(4)# -> frame_no_transaction$cluster

frame_no_transaction$cluster <- cluster$cluster

save(frame_no_transaction,file = 'processed_files/frame_no_transaction')
```

## Join frames with transactions:

```{r echo = FALSE, warning=FALSE}

# Join previus frame with transactionns
frame <- transaction %>% left_join(frame_no_transaction, by = 'account_id')


save(frame,file = 'processed_files/frame')
```