#Client Profile

```{r echo=FALSE, warning=FALSE, error=FALSE, include=FALSE}

library(plotly)
library(ggplot2)

load('processed_files/frame_no_transaction')

```

##Birth Date
```{r fig.cap='Distribution of birth date', echo=FALSE, warning=FALSE, error=FALSE}


p <- ggplot(data = frame_no_transaction) +
  geom_histogram(mapping = aes(x  = birth_date),bins = 20, )  +
  labs(x='Birth Date',y = '')

ggplotly(p)


```
##Gender
```{r fig.cap='Gender Distribution', echo=FALSE, warning=FALSE, error=FALSE}

p <- ggplot(data = frame_no_transaction) +
  geom_bar(mapping = aes(x  = gender)) +
  labs(x='Gender',y = '')


ggplotly(p)
```

##Number of Dependents
```{r fig.cap='Number of Dependents', echo=FALSE, warning=FALSE, error=FALSE}

p <- ggplot(data = frame_no_transaction) +
  geom_bar(mapping = aes(x  = dependants)) +
  labs(x='dependants',y = '')


ggplotly(p)
```

##Acount creation by time
```{r fig.cap='Distribution of birth date', echo=FALSE, warning=FALSE, error=FALSE}


p <- ggplot(data = frame_no_transaction) +
  geom_histogram(mapping = aes(x  = date.x, fill = gender),bins = 20, )  +
  labs(x='Cration date',y = '')

ggplotly(p)


```

##Age at account creation
```{r fig.cap='Distribution of birth date', echo=FALSE, warning=FALSE, error=FALSE}




p <- ggplot(data = mutate(frame_no_transaction,age_at_creation = (frame_no_transaction$date.x - frame_no_transaction$birth_date) / 365)) +
  geom_histogram(mapping = aes(x  = age_at_creation, fill = gender),bins = 10 )  +
  labs(x='Age at account creation',y = '')+
  scale_x_continuous()

ggplotly(p)


```

##Region
```{r fig.cap='Clients by Region', echo=FALSE, warning=FALSE, error=FALSE}

p <- ggplot(data = frame_no_transaction) +
  geom_bar(mapping = aes(x  = region)) +
  labs(x='Region',y = '')+
  theme(axis.text.x = element_text(size = 6))


ggplotly(p)
```



```{r fig.cap='Clients by Region', echo=FALSE, warning=FALSE, error=FALSE}

p <- ggplot(
  data = frame_no_transaction %>% group_by(district_name) %>% summarise(clients = n(), inhabitants = mean(inhabitants), ratio_urban = mean(`ratio of urban inhabitants`), region = first(region)) %>% dplyr::filter(district_name !='Hl.m. Praha')
            ) +
  geom_point(mapping = aes(x  = clients, y = inhabitants/1e3, name = district_name, size = ratio_urban, fill = region ),
             alpha = 0.6) + 
  geom_smooth(method='lm',aes(x  = clients, y = inhabitants/1e3) ) +
  labs(x='Clients',y = 'Inhabitants (thousands)')

ggplotly(p)
```





##Frequency of statements
```{r fig.cap='Frequency of statements', echo=FALSE, warning=FALSE, error=FALSE}

p <- ggplot(data = frame_no_transaction) +
  geom_bar(mapping = aes(x  = frequency)) +
  labs(x='frequency',y = '')


ggplotly(p)

```

```{r fig.cap='Frequency of statements', echo=FALSE, warning=FALSE, error=FALSE}

p <- ggplot(data = frame_no_transaction) +
  geom_boxplot(mapping = aes(x  = frequency, y = birth_date, fill = frequency)) +
  labs(x='frequency',y = '')


ggplotly(p)

```












