#Loans

```{r echo=FALSE, warning=FALSE, error=FALSE, include=FALSE}

library(plotly)
library(ggplot2)

f <- dplyr::filter(frame_no_transaction, !is.na(status))

```

##Loans Status

```{r fig.cap='Loan Satus', echo=FALSE, warning=FALSE, error=FALSE}


p <- ggplot(data = f) +
  geom_bar(mapping = aes(x  = status, fill = status) )  +
  labs(x='Loan Satus',y = '')

ggplotly(p)


```

```{r fig.cap='Distribution of birth date', echo=FALSE, warning=FALSE, error=FALSE}


p <- ggplot(data = f) +
  geom_histogram(mapping = aes(x  = date.y , fill = status),bins = 20, )  +
  labs(x='Loan Satus',y = '')

ggplotly(p)


```

```{r fig.cap='Distribution of birth date', echo=FALSE, warning=FALSE, error=FALSE}




p <- ggplot(data = mutate(f,age_at_loan = (f$date.y - f$birth_date) / 365)) +
  geom_histogram(mapping = aes(x  = age_at_loan, fill = status),bins = 10, )  +
  labs(x='Age at Loan',y = '')

ggplotly(p)


```

```{r fig.cap='Distribution of birth date', echo=FALSE, warning=FALSE, error=FALSE}




p <- ggplot(data = mutate(f,age_at_loan = (f$date.y - f$birth_date) / 365)) +
  geom_boxplot(mapping = aes(y  = age_at_loan, x = status, fill = status),bins = 10, )  +
  labs(x='Age at Loan',y = '')

ggplotly(p)


```




