---
title: "Join Frames"
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tidyr)
library(dplyr)
library(lubridate)

#Load files
load('processed_files/account')
load('processed_files/card')
load('processed_files/client')
load('processed_files/demographic')
load('processed_files/disposition')
load('processed_files/loan')
load('processed_files/order')
#load('processed_files/transaction')
```

## Join frames without transactions




```{r, echo = FALSE, warning = FALSE}

#Base frame accounts 
frame_no_transaction <- account %>%
  #Join accounts
  left_join(loan, by = 'account_id') %>%
  #Join Demographie
  left_join(demographic, by = 'district_id') %>%
  #Join disposition
  left_join(
    dplyr::filter(disposition, type == 'OWNER' ) %>% 
      left_join(disposition %>% group_by(account_id) %>% summarise(dependants = n()-1), by = 'account_id')
    , by = 'account_id') %>%
  #Join client
  left_join(client,by = 'client_id') %>%
  #Join card
  left_join(card, by = 'disp_id')

save(frame_no_transaction,file = 'processed_files/frame_no_transaction')

```

